---
- name: First Network Playbook
  connection: network_cli
  gather_facts: fals
  tasks:
    - name: show version
      ios_command:
        commands: show version
      when: ansible_network_os == 'ios'

      register: output_cisco

    - name: show output
      debug:
        var: output_cisco.stdout

    - name: show version
      junos_command:
        commands: show version
      when: ansible_network_os == 'junos'

      register: output_juniper

    - name: show output
      debug:
        var: output_juniper.stdout
